### ISSUE TITLE
highlighting can be spotty for multi-line strings

### ISSUE THREAD

**Issue by vitiral** [cespare/vim-toml#22]
Hey, I've been having problems with this library for multiline strings for a while where sometimes it highlights the wrong areas. This moslty happened when I scrolled with `<C-d>` or used search.

I added the following to my .vimrc and it now always highlights correctly all the time:
```
autocmd FileType toml
        \ autocmd BufEnter <buffer> syntax sync fromstart
```

As I understand it, this forces the syntax highlighting to always highlight from the top of the file.

However, this is obviously not efficient -- it would be much better if it was only executed on when the buffer is read/created. I tried `autocmd BufNew` and `autocmd BufEnter` but they didn't seem to work. I'm not a vim-Buf (haha, get it?). 

I would appreciate any help. Also, you could consider adding something like the above to the plugin to avoid these issues.

Thanks!

**Comment by cespare** [comment]
I added `syn sync minlines=500`. If you have multi-line strings that are more than 500 lines long, you might still notice the issues. I think 500 is an okay tradeoff for performance vs. correctness (other plugins I'm using seem to use between 200 and 2000).

Unfortunately triple-quoted strings makes this a hard problem. I don't think it's possible to write a `syn sync match` that will solve it in a better way.

**Comment by vitiral** [comment]
Thanks! Things are working much better now!

I'm curious why not 2000? I feel like toml syntax is fairly simple, so 2000 shouldn't be TOO much of a load.

I wrote a [design documentation tool](https://github.com/vitiral/artifact) that uses toml as it's default format and sometimes a design doc could extend more than 500 lines.

If not, what do you think the best way to customize your .vimrc to handle literal strings of any length?

**Comment by vitiral** [comment]
It looks like this is the best workaround:

```
autocmd FileType toml
    \ autocmd Syntax <buffer> syntax sync fromstart
```

**Comment by cespare** [comment]
If you have 500+-line multi-line strings, you're using TOML in a pretty unusual way :)

**Comment by vitiral** [comment]
Ya, that might be true :)
