### ISSUE TITLE
Syntax highlighting incorrect for comments that include an "=" sign

### ISSUE THREAD

**Issue by Juboal** [cespare/vim-toml#30]
Comments are not correctly highlighted if they include an equals "=" sign:

```
#Comment with equals sign does not work: x=0
#Comment with minus sign does work: x-0
#Comments with other special characters work:x !@$%^&*()_?>.,<>;:\|~`
```
The resulting highlighting errors can be seen in this screenshot:
![vim-toml-comments-highlighting_error](https://user-images.githubusercontent.com/38244748/38548912-3a862414-3cb3-11e8-8676-ce5e8c09c2c6.png)

It would be great if you could fix this or provide a work around.
Thanks in advance :-)

**Comment by cespare** [comment]
Thanks for reporting @Juboal!

I probably won't have time to look at this soon, but I'll happily accept a PR (from you or anyone else).

**Comment by cespare** [comment]
This seems to have been fixed in the meantime. All these examples are correctly highlighted as tomlComment now. Here's a screenshot:

![screen_20181127131921](https://user-images.githubusercontent.com/318501/49112266-29a3ca80-f247-11e8-93a7-a5418df6beb5.png)
