### ISSUE TITLE
Filetype not being detected (Cargo.toml, rust.vim)

### ISSUE THREAD

**Issue by twe4ked** [cespare/vim-toml#50]
I ran into the same issue in #48, an older version of rust.vim was overriding the filetype setting. Updating the plugin fixed the issue.

> I saw that rust.vim used to set filetype=cfg for its Cargo.toml file. (This is supposed to give a slightly better syntax than whatever vim's default if the user doesn't have any special toml handling.) In March rust.vim fixed their ftdetect to use the setf FALLBACK mechanism for this purpose.
> – https://github.com/cespare/vim-toml/issues/48#issuecomment-564722096

It took my a few mins to find an existing issue so I thought I'd create this so hopefully others can find it more easily.

**Comment by cespare** [comment]
Thanks for the SEO :)
